package com.gdx.orion.entities;

public enum EntityType {
	ASTEROID,BULLET,SHIP,WORLD_BOUNDRY,DELETEME, GRAVITY_WELL, GRAPPLE, SHIELD, COMET, PRE_FRAG_ASTEROID, ASTEROID_FRAGMENT, COMET_FRAGMENT, PRE_FRAG_COMET, DESTROYME_ASTEROID, DESTROYME_COMET
}
